export const ACTION = {
  EMAIL_LOGIN_REQUEST: "EMAIL_LOGIN_REQUEST",
  EMAIL_LOGIN_SUCCESS: "EMAIL_LOGIN_SUCCESS",
  EMAIL_LOGIN_FAILURE: "EMAIL_LOGIN_FAILURE",

  FACEBOOK_LOGIN_REQUEST: "FACEBOOK_LOGIN_REQUEST",
  FACEBOOK_LOGIN_FAILURE: "FACEBOOK_LOGIN_FAILURE",
  FACEBOOK_LOGIN_SUCCESS: "FACEBOOK_LOGIN_SUCCESS",

  GOOGLE_LOGIN_REQUEST: "GOOGLE_LOGIN_REQUEST",
  GOOGLE_LOGIN_SUCCESS: "GOOGLE_LOGIN_SUCCESS",
  GOOGLE_LOGIN_FAILURE: "GOOGLE_LOGIN_FAILURE",

  EMAIL_LOGOUT_REQUEST: "EMAIL_LOGOUT_REQUEST",
  EMAIL_LOGOUT_SUCCESS: "EMAIL_LOGOUT_SUCCESS",
  EMAIL_LOGOUT_FAILURE: "EMAIL_LOGOUT_FAILURE",

  EMAIL_SIGNUP_REQUEST: "EMAIL_SIGNUP_REQUEST",
  EMAIL_SIGNUP_SUCCESS: "EMAIL_SIGNUP_SUCCESS",
  EMAIL_SIGNUP_FAILURE: "EMAIL_SIGNUP_FAILURE",

  FORGOT_PASSWORD: "FORGOT_PASSWORD",
};
